#!/usr/bin/env bash

if [[ -z ${WAYLAND_DISPLAY} ]]; then
    pkexec btrfs-assistant --xdg-desktop=$XDG_CURRENT_DESKTOP
else
    yad --title="Password" --text="Enter password to run <b>btrfs-assistant</b> with sudo" --image="dialog-password" --entry --hide-text | sudo -SE btrfs-assistant
fi
